# How to create a vector in Python using NumPy
https://www.geeksforgeeks.org/how-to-create-a-vector-in-python-using-numpy/

## Vector
Vector are built from components, which are ordinary numbers. We can think of a vector as a list of numbers, and vector algebra as operations performed on the numbers in the list. In other words vector is the numpy 1-D array.

In [8]:
# importing numpy 
import numpy as np

# creating a 1-D list (Horizontal) 
list1 = [1, 2, 3]

# creating a 1-D list (Vertical) 
list2 = [[10],
         [20],
         [30]]

# creating a vector1 
# vector as row 
vector1 = np.array(list1)

# creating a vector 2 
# vector as column 
vector2 = np.array(list2)


# showing horizontal vector 
print("Horizontal Vector")
print(vector1)
print(vector1.shape)

print("----------------")

# showing vertical vector 
print("Vertical Vector")
print(vector2)
print(vector2.shape)


Horizontal Vector
[1 2 3]
(3,)
----------------
Vertical Vector
[[10]
 [20]
 [30]]
(3, 1)


In [9]:
print(np.dot(vector1, vector2))

[140]


In [10]:
print(np.dot(vector2, vector1))


ValueError: shapes (3,1) and (3,) not aligned: 1 (dim 1) != 3 (dim 0)

In [12]:
vector1.T

array([1, 2, 3])

In [13]:
vector2.T

array([[10, 20, 30]])

In [4]:


# importing numpy 
import numpy as np

# creating a 1-D list (Horizontal) 
list1 = [5, 6, 9]

# creating a 1-D list (Horizontal) 
list2 = [1, 2, 3]

# creating first vector 
vector1 = np.array(list1)

# printing vector1 
print("First Vector          : " + str(vector1))

# creating second vector 
vector2 = np.array(list2)

# printing vector2 
print("Second Vector         : " + str(vector2))

# adding both the vector 
# a + b = (a1 + b1, a2 + b2, a3 + b3) 
addition = vector1 + vector2

# printing addition vector 
print("Vector Addition       : " + str(addition))

# subtracting both the vector 
# a - b = (a1 - b1, a2 - b2, a3 - b3) 
subtraction = vector1 - vector2

# printing addition vector 
print("Vector Subtraction   : " + str(subtraction))

# multiplying  both the vector 
# a * b = (a1 * b1, a2 * b2, a3 * b3) 
multiplication = vector1 * vector2

# printing multiplication vector 
print("Vector Multiplication : " + str(multiplication))

# dividing  both the vector 
# a / b = (a1 / b1, a2 / b2, a3 / b3) 
division = vector1 / vector2

# printing division vector 
print("Vector Division       : " + str(division)) 


First Vector          : [5 6 9]
Second Vector         : [1 2 3]
Vector Addition       : [ 6  8 12]
Vector Subtraction   : [4 4 6]
Vector Multiplication : [ 5 12 27]
Vector Division       : [5. 3. 3.]


In [5]:
# importing numpy 
import numpy as np

# creating a 1-D list (Horizontal) 
list1 = [5, 6, 9]

# creating a 1-D list (Horizontal) 
list2 = [1, 2, 3]

# creating first vector  
vector1 = np.array(list1)

# printing vector1 
print("First Vector  : " + str(vector1))

# creating second vector 
vector2 = np.array(list2)

# printing vector2 
print("Second Vector : " + str(vector2))

# getting dot product of both the vectors 
# a . b = (a1 * b1 + a2 * b2 + a3 * b3) 
# a . b = (a1b1 + a2b2 + a3b3) 
dot_product = vector1.dot(vector2) 
  

First Vector  : [5 6 9]
Second Vector : [1 2 3]
