# TensorFlow 2 quickstart for beginners
https://www.tensorflow.org/tutorials/quickstart/beginner

In [3]:
import tensorflow as tf
print(tf.__version__)

2.16.1


In [8]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


In [9]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

u:\projects\learn-programming\python\tensorflow-lab\.venv\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [14]:
x_train[:1]

array([[[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.

In [15]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.22839412, -0.7339198 ,  0.9695134 , -0.09812802, -0.12911347,
        -0.21278599, -0.3106643 , -0.42558405,  0.21670361, -0.2531561 ]],
      dtype=float32)

In [16]:
tf.nn.softmax(predictions).numpy()


array([[0.08029647, 0.04843391, 0.26603645, 0.09146825, 0.08867753,
        0.08155959, 0.0739549 , 0.06592619, 0.12531412, 0.07833259]],
      dtype=float32)

In [17]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [18]:
loss_fn(y_train[:1], predictions).numpy()


2.5064213

In [19]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [20]:
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.8624 - loss: 0.4729
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9538 - loss: 0.1546
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9683 - loss: 0.1071
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9739 - loss: 0.0844
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9786 - loss: 0.0719


In [21]:
model.evaluate(x_test,  y_test, verbose=2)


313/313 - 0s - 907us/step - accuracy: 0.9749 - loss: 0.0772


[0.07720547914505005, 0.9749000072479248]

In [22]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [23]:
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.0856117e-09, 2.5991493e-09, 1.4174625e-06, 2.8080414e-05,
        1.1248758e-10, 3.2227724e-08, 2.1043444e-14, 9.9996948e-01,
        2.7263698e-09, 9.1179447e-07],
       [5.3338063e-09, 1.0493192e-04, 9.9988294e-01, 1.1471812e-05,
        2.0458172e-14, 5.8363594e-07, 1.0007644e-08, 4.0005315e-13,
        8.1621323e-08, 2.7562273e-13],
       [5.2283884e-08, 9.9874300e-01, 3.1588547e-04, 2.1061993e-05,
        9.9206518e-06, 3.0088881e-05, 1.8676534e-05, 6.8310753e-04,
        1.7768762e-04, 5.7652886e-07],
       [9.9897540e-01, 1.9882766e-08, 9.0441218e-04, 3.9302454e-06,
        2.3607583e-06, 3.8568214e-05, 3.1552576e-05, 1.3942370e-05,
        6.1438554e-06, 2.3627981e-05],
       [3.4960015e-06, 3.6353163e-09, 3.3929562e-05, 1.7809325e-07,
        9.9738818e-01, 8.7189989e-07, 2.1432685e-05, 1.4001386e-04,
        1.1264662e-05, 2.4006367e-03]], dtype=float32)>