# Tensor Basics
https://www.youtube.com/watch?v=PcstG8qiObc&list=PLqnslRFeH2Uqfv1Vz3DqeQfy0w20ldbaV&index=2

## variables

In [6]:
print('Hello Tensor')

Hello Tensor


In [7]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [9]:
import tensorflow as tf

In [10]:
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [12]:
x = tf.constant(4, shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [14]:
# rank 1
x = tf.constant([1, 2, 3])
print(x)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [16]:
# rank 2
x = tf.constant([[1, 2, 3], [4, 5, 6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [17]:
x  = tf.ones((3, 3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [18]:
x  = tf.zeros((3, 3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [21]:
x = tf.eye(3, 3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [24]:
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [25]:
x = tf.eye(3, 2)
print(x)

tf.Tensor(
[[1. 0.]
 [0. 1.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [26]:
x = tf.random.normal((3,3), mean=0, stddev=1)
print(x)

tf.Tensor(
[[-1.1154423   0.2908547  -0.7887753 ]
 [-1.5667354  -0.2172411   0.5380029 ]
 [-0.49159503  1.3989723  -1.0027454 ]], shape=(3, 3), dtype=float32)


In [29]:
x = tf.random.uniform((3, 3), minval=0, maxval=1)
print(x)

tf.Tensor(
[[0.9614774  0.9505819  0.43348765]
 [0.8884506  0.46545303 0.7169461 ]
 [0.3433348  0.6409656  0.16994691]], shape=(3, 3), dtype=float32)


In [30]:
x = tf.range(10)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [31]:
x = tf.cast(x, dtype=tf.float32)
print(x)

tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float32)


## Operators

elementwise

In [32]:
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])
z = tf.add(x, y)
print(z)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [33]:
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])
z = x + y
print(z)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [34]:
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])
z = tf.subtract(x, y)
print(z)

tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [35]:
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])
z = x - y
print(z)

tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [36]:
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])
z = x * y
print(z)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [37]:
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])
z = tf.multiply(x ,  y)
print(z)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [38]:
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])
z = tf.divide(x ,  y)
print(z)

tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [39]:
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])
z = x / y
print(z)

tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [42]:
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])
z = tf.tensordot(x, y, axes=1)
print(z)

tf.Tensor(32, shape=(), dtype=int32)


In [43]:
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])
z = tf.tensordot(x, y, axes=0)
print(z)

tf.Tensor(
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]], shape=(3, 3), dtype=int32)


In [44]:
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])
z = x ** 3
print(z)

tf.Tensor([ 1  8 27], shape=(3,), dtype=int32)


In [45]:
x = tf.random.normal((2, 2))
y = tf.random.normal((2, 2))
z = tf.matmul(x, y)
print(z)

tf.Tensor(
[[-0.2461178  -0.37827995]
 [ 0.87481    -0.3692929 ]], shape=(2, 2), dtype=float32)


In [46]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])
y = tf.constant([[1, 2], [3, 4], [5, 6]])
z = tf.matmul(x, y)
print(z)

tf.Tensor(
[[22 28]
 [49 64]], shape=(2, 2), dtype=int32)


In [47]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))
z = tf.matmul(x, y)
print(z)

tf.Tensor(
[[-0.68093437 -1.2435968  -0.949322    0.5259917 ]
 [-1.0895997  -3.567285   -0.7264717  -0.11978579]], shape=(2, 4), dtype=float32)


In [48]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))
z = x @ y
print(z)

tf.Tensor(
[[-0.70847106 -0.5917691   0.8719347   2.1929414 ]
 [-0.37555987 -0.4519015   0.9904592   1.0418139 ]], shape=(2, 4), dtype=float32)
