# numpy.matmul
https://numpy.org/doc/stable/reference/generated/numpy.matmul.html#numpy-matmul

numpy.matmul(x1, x2, /, out=None, *, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj, axes, axis]) = <ufunc 'matmul'>

Matrix product of two arrays.

Parameters:

    x1, x2array_like

        Input arrays, scalars not allowed.
    outndarray, optional

        A location into which the result is stored. If provided, it must have a shape that matches the signature (n,k),(k,m)->(n,m). If not provided or None, a freshly-allocated array is returned.
    **kwargs

        For other keyword-only arguments, see the ufunc docs.

        New in version 1.16: Now handles ufunc kwargs

Returns:

    yndarray

        The matrix product of the inputs. This is a scalar only when both x1, x2 are 1-d vectors.

Raises:

    ValueError

        If the last dimension of x1 is not the same size as the second-to-last dimension of x2.

        If a scalar value is passed in.



In [1]:
import numpy as np

In [2]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])
np.matmul(a, b)

array([[4, 1],
       [2, 2]])

In [3]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([1, 2])
np.matmul(a, b)

array([1, 2])

In [4]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([1, 2])
np.matmul(b, a)

array([1, 2])

In [5]:
a = np.arange(2 * 2 * 4).reshape((2, 2, 4))
b = np.arange(2 * 2 * 4).reshape((2, 4, 2))
np.matmul(a,b).shape
np.matmul(a, b)[0, 1, 1]
sum(a[0, 1, :] * b[0 , :, 1])


98

In [6]:
np.matmul([2j, 3j], [2j, 3j])

(-13+0j)

In [7]:
np.matmul([2, 3j], [2j, 3j])

(-9+4j)

In [8]:
np.matmul([1,2], 3)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [9]:
np.matmul([1,2], [3])

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)

In [10]:
np.matmul([1], [2, 3])

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [11]:
np.matmul(1, [2, 3])

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [12]:
np.matmul([1, 1], [2, 3])

5

In [13]:
print("Hello driver D:")

Hello driver D:
