# NumPy quickstart
https://numpy.org/doc/stable/user/quickstart.html

## the basics

In [1]:
import numpy as np

### basic operations

#### @ operator
The matrix product can be performed using the @ operator (in python >=3.5) or the dot function 

matrix product

In [6]:
A = np.array([[1, 1],
              [0, 1]])

B = np.array([[2, 0],
              [3, 4]])

A @ B     # matrix product

array([[5, 4],
       [3, 4]])

#### dot function

In [8]:
A = np.array([[1, 1],
              [0, 1]])

B = np.array([[2, 0],
              [3, 4]])

A.dot(B) # another matrix product

array([[5, 4],
       [3, 4]])

In [7]:
A = np.array([[1, 1],
              [0, 1]])

B = np.array([[2, 0],
              [3, 4]])

np.dot(A, B) # another matrix product

array([[5, 4],
       [3, 4]])